### ISSUE TITLE
httptrace middleware for normal HTTP handleFunc

### ISSUE THREAD

**Issue by Unknwon** [sourcegraph/appdash#79]
Hi, if I'm not misreading anything, the `httptrace` package [only supports Negroni](https://sourcegraph.com/sourcegraph.com/sourcegraph/appdash@e9d282715158e834466db6c848dc70491bb816c3/.tree/httptrace/server.go#startline=68&endline=68)? Is there a way to directly return a HTTP handleFunc or I have to wrap up myself?

Thanks!

**Comment by slimsag** [comment]
I appreciate the question! :+1: 

It is compatible with Negroni, but you do not _have to_ use Negroni. You can initialize it like so in your package somewhere:

```
var middleware = httptrace.Middleware(myCollector, &httptrace.MiddlewareConfig{
    ...config funcs to set route name etc...
})
```

And then to wrap a `http.HandlerFunc` you could write:

```
func wrap(next http.HandlerFunc) http.HandlerFunc {
    return func(w http.ResponseWriter, r *http.Request) {
        middleware(w, r, next)
    }
}

http.HandleFunc("/bar", wrap(func(w http.ResponseWriter, r *http.Request) {
	fmt.Fprintf(w, "Hello, %q", html.EscapeString(r.URL.Path))
}))
```

In general I do not suggest this approach because it means you must write `wrap()` on every HTTP handler, basically doing what Negroni does for you manually.

Maybe you have a suggestion on how it can be improved? If so I would really like to hear! :)

**Comment by Unknwon** [comment]
Thanks your answer!

I think I've get what I need.
